spring.application.name: media-service

server:
  port: 8100

minio:
  server:
    url: http://34.101.39.118:5430
    access-key: minioadmin
    secret-key: minioadmin123
    bucket-name: files

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/media
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

media.url: http://localhost:8100/api/v1/files/preview
